CREATE TABLE `apk` (
	`id` int(11) NOT NULL, 
	`name` VARCHAR(255) DEFAULT NULL, 
	`star` VARCHAR(255) DEFAULT NULL, 
	`down_num` VARCHAR(255) DEFAULT NULL, 
	`url` VARCHAR(255) DEFAULT NULL, 
	PRIMARY KEY (`id`)
) CHARACTER SET = 'UTF8';
