CREATE TABLE `ask` (
	`id` INT(11) UNSIGNED NOT NULL, 
	`title` TEXT DEFAULT NULL, 
	`classname` TEXT DEFAULT NULL, 
	`keywords` TEXT DEFAULT NULL,
	`weight` TEXT DEFAULT NULL,
	PRIMARY KEY (`id`)
) CHARACTER SET = 'UTF8';
